[theme]
# Primary accent for interactive elements
primaryColor = "#ec8630"

# Background color for the main content area
backgroundColor = "#331D2C"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#3F2E3E"

# Color used for almost all text
textColor = "#FFFFFF"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"