testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51Nf0mqIIBa1FWZAvvNdVvDaSe3JNSwcE1P8LCQAgobx8FQhsJdXuudw6jsMgwzrpuWzGIVvsa2R0NgyXxgQbwFJ5007sKm3w4f" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_5kA7tY5G190X5ji5kk" #only needed if using Stripe
client_id = "583174104574-9tssqoddfieu8tc3pl2gse454rv5sl1o.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://your_app_url..."